### ISSUE TITLE
Bug in HttpServerConfigurationProvidingConfiguration - wrong SSL options mapping

### ISSUE THREAD

**Issue by constantin-teodorescu** [oli-d/nova#31]
The name of the bean methods doesn't correspong with the key returned from environment resulting a mess up.

   @Bean("httpServerTrustStore")
    public String sslTrustStore**Pass(**) { // it should be sslTrustStorePath
        return environment.getProperty("NOVA.HTTP.SERVER.TRUST_STORE");
    }
    @Bean("httpServerTrustStorePass")
    public String sslTrustStore**Path**() { // is shold be sslTrustStorePass
        return environment.getProperty("NOVA.HTTP.SERVER.TRUST_STORE_PASS");
    }

Exactly the same problem is with key store options:

   @Bean("httpServerKeyStore")
    public String sslKeyStore**Pass**() { // is shold be sslKeyStorePath
        return environment.getProperty("NOVA.HTTP.SERVER.KEY_STORE");
    }
    @Bean("httpServerKeyStorePass")
    public String sslKeyStore**Path**() {// is shold be sslKeyStorePass
        return environment.getProperty("NOVA.HTTP.SERVER.KEY_STORE_PASS");
    }

**Comment by oli-d** [comment]
Fixed in 8.0.0
